// Generated by scripts/gen-abi.mjs from pinarc-contracts/src/PinarcConfig.sol — do not edit by hand.
export const PinarcConfigAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "treasury_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "curve",
    "inputs": [],
    "outputs": [
      {
        "name": "virtualTokens",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "curveSupply",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "lpSupply",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "graduationUsdg",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fees",
    "inputs": [],
    "outputs": [
      {
        "name": "tradeFeeBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "creatorShareBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "graduationFeeBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "launchFee",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "treasury",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "guardian",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "guards",
    "inputs": [],
    "outputs": [
      {
        "name": "batchSeconds",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "antiSniperSeconds",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "cooldownSeconds",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "maxWalletBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxTxBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxBatchCommitBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxFloorBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxTeamBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "minBond",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "bondLockSeconds",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setCurveParams",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct PinarcConfig.CurveParams",
        "components": [
          {
            "name": "virtualTokens",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "curveSupply",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lpSupply",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "graduationUsdg",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeParams",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct PinarcConfig.FeeParams",
        "components": [
          {
            "name": "tradeFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "creatorShareBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "graduationFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "launchFee",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGuardParams",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct PinarcConfig.GuardParams",
        "components": [
          {
            "name": "batchSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "antiSniperSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cooldownSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxWalletBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxTxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxBatchCommitBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxTeamBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minBond",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "bondLockSeconds",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGuardian",
    "inputs": [
      {
        "name": "guardian_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalSupply",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "CurveParamsSet",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct PinarcConfig.CurveParams",
        "components": [
          {
            "name": "virtualTokens",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "curveSupply",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lpSupply",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "graduationUsdg",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeParamsSet",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct PinarcConfig.FeeParams",
        "components": [
          {
            "name": "tradeFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "creatorShareBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "graduationFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "launchFee",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GuardParamsSet",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct PinarcConfig.GuardParams",
        "components": [
          {
            "name": "batchSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "antiSniperSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cooldownSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxWalletBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxTxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxBatchCommitBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxTeamBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minBond",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "bondLockSeconds",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GuardianSet",
    "inputs": [
      {
        "name": "guardian",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;
