// Regenerates src/abi/*.ts from the compiled pinarc-contracts artifacts (`forge build` there first).
// Usage: CONTRACTS=../pinarc-contracts pnpm gen-abi
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const contracts = resolve(process.env.CONTRACTS ?? "../pinarc-contracts");
const names = ["PinarcFactory", "BondingCurve", "PinarcToken", "PinarcConfig", "CreatorBond", "FloorReserve", "LPLocker", "VestingVault"];
let index = "// Generated by scripts/gen-abi.mjs from pinarc-contracts — do not edit by hand.\n";
for (const n of names) {
  const abi = JSON.parse(readFileSync(resolve(contracts, `out/${n}.sol/${n}.json`), "utf8")).abi;
  writeFileSync(resolve("src/abi", `${n}.ts`), `// Generated by scripts/gen-abi.mjs from pinarc-contracts/src/${n}.sol — do not edit by hand.\nexport const ${n}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`);
  index += `export { ${n}Abi } from "./${n}.js";\n`;
}
index += `export { erc20Abi } from "./erc20.js";\n`;
writeFileSync(resolve("src/abi/index.ts"), index);
console.log(`wrote ${names.length} ABIs`);
